logs:
  - name: root
    level: info
    formatter: "%d %m %n"
    appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdOutLogAppender
  - name: system
    level: info
    formatter: "%d [%p] %f:%l %m %n"
    appender:
      - type: StdOutLogAppender

system:
  port: 8080
  vec: [10, 20]
  