logs:
  - name: root
    level: info
    formatter: "%d %m %n"
    appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdOutLogAppender
  - name: system
    level: info
    formatter: "%d [%p] %f:%l %m %n"
    appender:
      - type: StdOutLogAppender

system:
  port: 8080
  vec: [10, 20]
  list: [30, 40]
  set: [50, 60]
  uset: [70, 80, 80]
  map:
    nine: 90
    ten: 100
  umap:
    eleven: 110
    twelve: 120

  