logs:
  - name: root
    level: info
    formatter: "%d %m %n"
    appenders:
      - type: FileLogAppender
        file: log.txt
        formatter: "%d %m %n"
      - type: StdOutLogAppender
  - name: system
    level: info
    formatter: "%d [%p] %f:%l %m %n"
    appenders:
      - type: StdOutLogAppender

system:
  port: 8080
  vec: [10, 20]
  list: [30, 40]
  set: [50, 60]
  uset: [70, 80, 80]
  map:
    nine: 90
    ten: 100
  umap:
    eleven: 110
    twelve: 120

class:
  person:
    name: "yue"
    age: 25
    man: true
  map:
    yue01:
      name: "yue01"
      age: 25
      man: true
    yue02:
      name: "yue02"
      age: 30
      man: false

  